(() => {
 'use strict';
 const figures=window.CHARACTERS,questions=window.LAB_QUESTIONS,key='hre4m1-character-lab-v1';
 const empty=()=>({groupName:'',members:'',selected:null,phase:0,question:0,responses:['','',''],distinction:'',check:null,opening:''});
 let state=empty(),storage=true,viewed='aslan',category='All';
 try {const v=JSON.parse(localStorage.getItem(key)||'null');if(v&&typeof v==='object'){state={...state,...v};if(v.custom?.id==='custom'&&typeof v.custom.name==='string'&&typeof v.custom.intro==='string'&&Array.isArray(v.custom.events)&&Array.isArray(v.custom.sources))figures.push(v.custom);state.responses=questions.map((_,i)=>typeof v.responses?.[i]==='string'?v.responses[i]:'');if(!figures.some(f=>f.id===state.selected))state.selected=null;if(!Number.isInteger(state.phase)||state.phase<0||state.phase>3)state.phase=0;if(!Number.isInteger(state.question)||state.question<0||state.question>2)state.question=0;for(const k of ['groupName','members','distinction','opening'])if(typeof state[k]!=='string')state[k]='';}}catch{storage=false;}
 if(state.selected)viewed=state.selected;
 const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[x]));
 const chosen=()=>figures.find(f=>f.id===state.selected),sourceHTML=f=>`<ul class="source-list">${f.sources.map(s=>`<li>${s.url?`<a href="${esc(s.url)}" target="_blank" rel="noopener noreferrer">${esc(s.title)}</a>`:esc(s.title)}${s.note?`<span class="source-note">${esc(s.note)}</span>`:''}</li>`).join('')}</ul>`;
 function toast(text){$('#toast').textContent=text;$('#toast').classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').classList.remove('show'),3000);}
 function save(){try{localStorage.setItem(key,JSON.stringify(state));storage=true;}catch{storage=false;}$('#saveStatus').textContent=storage?'Saved on this device · download before leaving.':'Saving is unavailable · download your work before leaving.';}
 $('#groupName').value=state.groupName;$('#members').value=state.members;
 for(const k of ['groupName','members'])$('#'+k).addEventListener('input',e=>{state[k]=e.target.value;save();});
 function head(n,title,desc,extra=''){return `<div class="page-head"><div><span class="phase-label">Phase ${n} of 4</span><h1>${title}</h1><p>${desc}</p></div>${extra}</div>`;}
 function nav(){const labels=['Explore the figures','Build your answers','Why Jesus is unique','Present your findings'];$('#steps').innerHTML=labels.map((s,i)=>`<button type="button" class="step" data-phase="${i}" ${state.phase===i?'aria-current="step"':''}><span>0${i+1}</span><span>${s}</span></button>`).join('');}
 function go(p){if(p>0&&!chosen()){toast('Choose a figure to begin your investigation.');return;}state.phase=p;save();render();$('#workspace').focus();}
 function profile(f){return `<article class="profile"><div class="profile-head"><p class="eyebrow">${esc(f.category)} · ${esc(f.origin)}</p><h2>${esc(f.name)}</h2><p>${esc(f.version)}</p></div><div class="profile-content"><h3>Who is this figure</h3><p>${esc(f.intro)}</p><h3>Actions to investigate</h3>${f.events.map(e=>`<div class="evidence"><strong>${esc(e.title)}</strong><p>${esc(e.text)}</p><small>${esc(e.ref)}</small></div>`).join('')}<h3>Possible echoes of Jesus</h3><p>${esc(f.connection)}</p><div class="prompt-note"><strong>Where the comparison has limits</strong><p>${esc(f.limit)}</p></div><h3>Discuss before you choose</h3><p>${esc(f.challenge)}</p><div class="sources"><strong>Profile sources and story version</strong><br>${sourceHTML(f)}</div><div class="profile-actions"><button type="button" class="primary" data-select="${f.id}">${state.selected===f.id?'Continue with this figure':'Investigate this figure'}</button><small>Read the evidence. Write your own explanation.</small></div></div></article>`;}
 function library(){const list=figures.filter(f=>category==='All'||f.category===category);return head(1,'Choose your subject.','Work in pairs or a group of three. Explore the profiles, discuss the evidence, and choose one figure.', '<div class="count">13<small>original suggested figures</small></div>')+`<div class="library-layout"><section class="library-nav" aria-label="Character library"><div class="library-controls"><label class="visually-hidden" for="category">Figure category</label><select id="category">${['All','Historical','Biblical','Fictional','Mythical','Legendary'].map(c=>`<option ${c===category?'selected':''}>${c}</option>`).join('')}</select><button id="surprise" type="button" class="quiet">Surprise us</button><button id="custom" type="button" class="quiet">Another figure</button></div><div class="figure-list">${list.map(f=>`<button type="button" class="figure-item" data-view="${f.id}" aria-pressed="${viewed===f.id}"><span><strong>${esc(f.name)}</strong><small>${esc(f.origin)}</small></span><span class="initial" aria-hidden="true">${esc(f.name.split(' ').map(x=>x[0]).slice(0,2).join(''))}</span></button>`).join('')}</div></section>${profile(figures.find(f=>f.id===viewed)||figures[0])}</div><p class="inline-note gap">Spoiler note: profiles describe important plot events. For a different figure, use “Another figure” and agree on your choice with your teacher.</p>`;}
 function lab(){
  const f=chosen(),q=questions[state.question],g=window.JESUS_SCENES[state.question];
  return head(2,'Build an evidence-based answer.',`Your subject: ${esc(f.name)}. Keep the original three questions at the centre of your investigation.`)+`
  <div class="task-nav" aria-label="Assignment questions">${questions.map((q,i)=>`<button type="button" data-question="${i}" aria-pressed="${state.question===i}">${i+1}. ${q.short}</button>`).join('')}</div>
  <div class="workspace-layout gospel-workspace">
   <section class="question-intro" aria-labelledby="assignmentQuestion"><h2 class="task-question" id="assignmentQuestion">${q.title}</h2><p class="answer-help">${q.help}</p></section>
   <aside class="reference-rail" aria-label="Jesus and character reference">
    <section class="side-reference jesus-reference" aria-labelledby="jesusReferenceHeading">
     <p class="eyebrow">Jesus reference</p><h3 id="jesusReferenceHeading">${esc(g.title)}</h3>
     <a class="gospel-reference" href="${esc(g.url)}" target="_blank" rel="noopener noreferrer">Read ${esc(g.reference)}</a>
     <h4>What Jesus did</h4><p>${esc(g.scene)}</p>
     <h4>Why it matters</h4><p>${esc(g.meaning)}</p>
     <div class="compare-prompt"><h4>Compare with ${esc(f.name)}</h4><p>${esc(g.compare)}</p></div>
     <details class="other-gospels"><summary>More Gospel connections</summary><ul class="gospel-list">${q.gospels.map(([r,t])=>`<li><strong>${r}</strong><br>${t}</li>`).join('')}</ul><p>You may also use an example from your Unit 1.4 notes.</p></details>
    </section>
    <details class="side-reference character-reference"><summary>Your figure · ${esc(f.name)}</summary><p>${esc(f.intro)}</p><h3>Evidence you can examine</h3>${f.events.map(e=>`<details><summary>${esc(e.title)}</summary><p>${esc(e.text)}</p><small>${esc(e.ref)}</small></details>`).join('')}</details>
   </aside>
   <section class="answer-workspace"><label for="answer" class="answer-label">Your group’s answer</label><p class="answer-help">Action or evidence → your explanation → connection to Jesus. Include the scene, source, or class-note reference.</p><textarea id="answer" class="answer" placeholder="Discuss together, then write in your own words…">${esc(state.responses[state.question])}</textarea><div class="actions"><button type="button" class="primary" id="nextQuestion">${state.question<2?'Next question':'Make the distinction'}</button><button type="button" class="quiet" data-phase="0">Review the full profile</button></div></section>
  </div>`;
 }

 function theology(){return head(3,'A resemblance is not an identity.','Use your comparison to explain the Catholic meaning of Incarnation.')+`<section class="theology"><p class="theology-intro">Only Jesus is truly God incarnate: the eternal Son of God who became human without ceasing to be God.</p><div class="distinction"><div><h2>A Christlike figure</h2><p>Can reflect a virtue or action of Jesus. A saint, prophet, hero, or literary symbol does not become divine by being loving, powerful, or self-sacrificing.</p></div><div><h2>Jesus Christ</h2><p>Is fully God and fully human in one divine person. The Incarnation concerns who Jesus is, not a score for how good someone is.</p></div></div><p class="inline-note">Read John 1:1–14 and <a href="https://www.vatican.va/archive/ENG0015/__P1J.HTM" target="_blank" rel="noopener noreferrer">Catechism of the Catholic Church 461–464, 480–483</a>.</p><h2 class="subheading">Quick check</h2><p>Which statement expresses the Catholic meaning of Incarnation?</p><div class="check-options">${['Someone becomes God by doing enough good things.','Jesus is partly God and partly human.','The eternal Son assumes human nature and remains fully God.'].map((t,i)=>`<button type="button" data-check="${i}" aria-pressed="${state.check===i}">${t}</button>`).join('')}</div>${state.check!==null?`<div class="feedback" role="status">${state.check===2?'Yes. Jesus is fully divine and fully human. Virtuous actions can resemble his actions without giving another figure his divine identity.':'Reconsider: the Incarnation is the eternal Son becoming truly human while remaining truly God. Goodness does not turn a person into God, and Jesus is not half God and half human.'}</div>`:''}<div class="prompt-note"><strong>Your figure · ${esc(chosen().name)}</strong><p>${esc(chosen().limit)}</p></div><label class="answer-label" for="distinction">Your group’s concluding explanation</label><p class="answer-help">Identify one limit of your comparison. Explain why your figure’s Christlike qualities do not make the figure God incarnate and why Jesus is unique.</p><textarea id="distinction" class="answer" placeholder="Our figure reflects Jesus when… The comparison has limits because… Only Jesus is God incarnate because…">${esc(state.distinction)}</textarea><div class="actions"><button class="primary" type="button" data-phase="3">Prepare the group presentation</button></div></section>`;}
 function report(){const f=chosen(),has=state.responses.map(x=>x.trim().length>0);return head(4,'Present your findings.',`${esc(f.name)} · Share your evidence, your answers, and the meaning of the Incarnation.`)+`<button type="button" class="quiet exit-present" id="exitPresent">Exit presentation</button><section class="report"><p class="report-meta">${esc(state.groupName||'Group name not entered')}${state.members?' · '+esc(state.members):''}</p><div class="prep"><h2>Ready to share</h2><p>Introduce the figure briefly. Answer all three questions using specific evidence. Finish by explaining why Christlike qualities do not make someone God incarnate. Every member contributes.</p><ul class="checklist">${questions.map((q,i)=>`<li class="${has[i]?'done':''}">Question ${i+1} · ${q.short}${has[i]?'':' · answer still needed'}</li>`).join('')}<li class="${state.distinction.trim()?'done':''}">Explain why only Jesus is God incarnate${state.distinction.trim()?'':' · conclusion still needed'}</li></ul><label for="opening" class="answer-label">Optional opening statement</label><textarea id="opening" class="answer" style="min-height:90px" placeholder="Introduce the figure and the strongest Christlike quality you found…">${esc(state.opening)}</textarea><div class="actions"><button type="button" class="primary" id="present">Presentation view</button><button type="button" class="quiet" id="download">Download group report</button><button type="button" class="quiet" id="print">Print or save PDF</button></div><p class="inline-note">Your report includes the answers you have written, even if unfinished. Download it before leaving a shared device.</p></div>${state.opening.trim()?`<h2>Our opening statement</h2><div class="response">${esc(state.opening)}</div>`:''}<h2>Who we investigated</h2><p>${esc(f.intro)}</p>${questions.map((q,i)=>`<h2>${i+1}. ${q.title}</h2><div class="response ${has[i]?'':'missing'}">${esc(state.responses[i]||'Your group has not written this answer yet.')}</div>`).join('')}<h2>Why Jesus alone is God incarnate</h2><div class="response ${state.distinction.trim()?'':'missing'}">${esc(state.distinction||'Your group has not written its concluding explanation yet.')}</div><div class="sources"><strong>Profile references</strong><br>${sourceHTML(f)}<br><a href="https://www.vatican.va/archive/ENG0015/__P1J.HTM" target="_blank" rel="noopener noreferrer">Catechism of the Catholic Church · 461–464, 480–483</a></div><div class="prep"><h2>Class discussion</h2><p>Ask another group: “Which action best supports your comparison, and why?” Be ready to defend or revise one connection after hearing classmates’ reasoning.</p><div class="actions"><button class="quiet" type="button" id="restart">Start a new group</button><a href="handouts/HRE4M1_Unit_1_4_Character_Lab.docx" download>Student Word handout</a></div></div></section>`;}
 function render(){if(state.phase>0&&!chosen())state.phase=0;nav();$('#workspace').innerHTML=[library,lab,theology,report][state.phase]();bind();}
 function bind(){const a=$('#answer');if(a)a.addEventListener('input',e=>{state.responses[state.question]=e.target.value;save();});for(const k of ['distinction','opening']){const e=$('#'+k);if(e)e.addEventListener('input',ev=>{state[k]=ev.target.value;save();});}$('#category')?.addEventListener('change',e=>{category=e.target.value;const list=figures.filter(f=>category==='All'||f.category===category);if(!list.some(f=>f.id===viewed))viewed=list[0].id;render();});}
 function choose(id){const f=figures.find(f=>f.id===id);if(!f)throw Error('Unknown figure');if(state.selected&&state.selected!==id&&(state.responses.some(t=>t.trim())||state.distinction.trim())){if(!confirm('Changing figures will clear your answers and conclusion. Download your existing report first if you want to keep it. Change figures?'))return false;state.responses=['','',''];state.distinction='';state.opening='';state.check=null;}state.selected=id;viewed=id;state.question=0;state.phase=1;save();render();$('#workspace').focus();return true;}
 function download(){const f=chosen(),text=['HRE4M1 Unit 1.4 · Echoes of the Incarnation',state.groupName,`Members: ${state.members}`,`Figure: ${f.name}`,`Version: ${f.version}`,state.opening?'\nOpening: '+state.opening:'',...questions.map((q,i)=>`\n${i+1}. ${q.title}\n${state.responses[i]||'[Not yet answered]'}`),`\nWhy Jesus alone is God incarnate\n${state.distinction||'[Not yet answered]'}`,'\nProfile references',...f.sources.map(s=>s.title+(s.url?'\n'+s.url:'')),'Catholic teaching: CCC 461–464, 480–483\nhttps://www.vatican.va/archive/ENG0015/__P1J.HTM'].filter(Boolean).join('\n');const url=URL.createObjectURL(new Blob([text],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='Character-Lab-'+f.id+'-Group-Report.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('Group report downloaded.');}
 document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.phase!==undefined){go(Number(b.dataset.phase));return;}if(b.dataset.view){viewed=b.dataset.view;render();return;}if(b.dataset.select){choose(b.dataset.select);return;}if(b.dataset.question!==undefined){state.question=Number(b.dataset.question);save();render();return;}if(b.dataset.check!==undefined){state.check=Number(b.dataset.check);save();render();return;}if(b.id==='surprise'){const list=figures.filter(f=>category==='All'||f.category===category);viewed=list[Math.floor(Math.random()*list.length)].id;render();toast('Read the profile before deciding.');}if(b.id==='custom'){$('#customDialog').showModal();}if(b.id==='nextQuestion'){if(state.question<2){state.question++;save();render();}else go(2);}if(b.id==='present'){render();document.body.classList.add('presenting');$('#exitPresent').focus();}if(b.id==='exitPresent'){document.body.classList.remove('presenting');render();$('#workspace').focus();}if(b.id==='download')download();if(b.id==='print')window.print();if(b.id==='restart'){if(confirm('Start a new group on this device? This clears the current answers. Download your report first if you want to keep it.')){state=empty();$('#groupName').value='';$('#members').value='';document.body.classList.remove('presenting');save();render();}}});
 $('#guideButton').addEventListener('click',()=>$('#guideDialog').showModal());$('#closeGuide').addEventListener('click',()=>$('#guideDialog').close());
 document.addEventListener('keydown',e=>{if(e.key==='Escape'&&document.body.classList.contains('presenting')){document.body.classList.remove('presenting');render();}});
 // The original permits other figures. A custom figure has no invented biography.
 const dialog=document.createElement('dialog');dialog.id='customDialog';dialog.innerHTML='<h2>Investigate another figure</h2><p>Agree on your choice with your teacher. Use your notes or a reliable source to learn who the figure is and identify specific actions. This app has prepared profiles for the original 13 suggestions.</p><form id="customForm"><label class="answer-label" for="customName">Figure name</label><input id="customName" maxlength="100" required><label class="answer-label" for="customBio">Who is the figure and which source or version are you using?</label><textarea id="customBio" class="answer" style="min-height:130px" maxlength="2500" required></textarea><div class="actions"><button class="primary" type="submit">Choose this figure</button><button class="quiet" type="button" id="cancelCustom">Cancel</button></div></form>';document.body.append(dialog);$('#cancelCustom').addEventListener('click',()=>dialog.close());$('#customForm').addEventListener('submit',e=>{e.preventDefault();const name=$('#customName').value.trim(),intro=$('#customBio').value.trim();if(!name||!intro)return;const custom={id:'custom',name,category:'Other',origin:'Group-selected figure',version:'Source or version supplied by your group',intro,events:[],connection:'Identify an action that suggests service, moral courage, or a Christlike virtue. Use a reliable source and explain your reasoning.',limit:'Sharing a virtue, having special powers, or being called a saviour does not make this figure God incarnate. Explain the limits of your particular comparison.',challenge:'What evidence supports your comparison, and what would make it weaker?',sources:[{title:'Source information supplied in your group profile'}]};const old=figures.findIndex(f=>f.id==='custom');if(state.selected==='custom'&&old>=0&&(figures[old].name!==name||figures[old].intro!==intro)&&(state.responses.some(t=>t.trim())||state.distinction.trim())){if(!confirm('Changing your custom figure will clear your current answers and conclusion. Continue?'))return;state.responses=['','',''];state.distinction='';state.opening='';state.check=null;}if(old>=0)figures.splice(old,1);figures.push(custom);if(choose('custom')){state.custom=custom;save();dialog.close();}});
 
 save();render();
})();
